In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline

# Assuming your data files are saved in "(your current directory)/io/" folder.

In [8]:
train = pd.read_csv("train.csv")
train.head()

,Donation ID,Donor ID,Donation Amount,Donation Received Date,# of Donations Made,min,max,Total Sum Donated,Donor State,Donor Is Teacher,...,School State,# Donations Received,Total Donation Amt Received,Teacher Project Posted Sequence,Project Title,Project Subject Category Tree,Project Subject Subcategory Tree,Project Resource Category,Project Current Status,Resource Vendor Name
0,579821d4de7922dd32ae6aa9f1e67fd9,00070fd37d3e8b5b7c08a4a0ba22aba1,50.00,2016-01-18 18:40:29,29,10.00,150.0,1560.00,Oklahoma,No,...,Oklahoma,8,375.00,5,Science Lab Supplies,Math & Science,"Applied Sciences, Health & Life Science",Supplies,Expired,"Carolina Biological Supply Company,Carolina Bi..."
1,f2bbdba4619801071b2e97a483ff2c71,00070fd37d3e8b5b7c08a4a0ba22aba1,50.00,2017-09-17 12:46:24,29,10.00,150.0,1560.00,Oklahoma,No,...,Oklahoma,6,370.13,2,Your Epidermis is Showing...Your Art!,Music & The Arts,Visual Arts,Supplies,Fully Funded,"Amazon Business,Amazon Business"
2,886fdf2feda0118c8f2adcac7b15b0e4,0015dc157335e5ad6f569e5264bbf33e,50.00,2016-01-10 10:11:22,22,10.00,2700.0,4505.86,Maryland,Yes,...,Maryland,5,718.28,20,Shine Some Light on the Subject!,"Special Needs, Music & The Arts","Special Needs, Visual Arts",Supplies,Fully Funded,"Amazon Business,Amazon Business,Amazon Busines..."
3,02216d6d22189b292fd6285285b95c12,0015dc157335e5ad6f569e5264bbf33e,41.00,2013-04-24 16:23:11,22,10.00,2700.0,4505.86,Maryland,Yes,...,Maryland,2,143.16,11,Repetition With Excitement!,"Applied Learning, Special Needs","Early Development, Special Needs",Books,Fully Funded,"AKJ Education,AKJ Education,AKJ Education,AKJ ..."
4,7798f746c2956bfd29f394b5b127e6a4,00199e3565635f8a5ebefd3b5985a7f3,238.65,2018-01-25 08:57:10,215,11.24,1116.4,46502.98,Massachusetts,No,...,Massachusetts,1,238.65,3,Teaching Kids Sports,Health & Sports,"Health & Wellness, Team Sports",Sports & Exercise Equipment,Fully Funded,"School Specialty,Staples Advantage,School Spec..."

## Identify Key Variables using Factor Analysis for Mixed Data

In [9]:
cosine_df = train[['Donor ID','Project ID','Donation Amount','Donor State','Donor Is Teacher','Project Grade Level Category','Project Cost','School Metro Type','School State','# Donations Received','Total Donation Amt Received','Teacher Project Posted Sequence','Project Subject Category Tree','Project Subject Subcategory Tree','Project Resource Category','Resource Vendor Name']]
cosine_df.head()

,Donor ID,Project ID,Donation Amount,Donor State,Donor Is Teacher,Project Grade Level Category,Project Cost,School Metro Type,School State,# Donations Received,Total Donation Amt Received,Teacher Project Posted Sequence,Project Subject Category Tree,Project Subject Subcategory Tree,Project Resource Category,Resource Vendor Name
0,00070fd37d3e8b5b7c08a4a0ba22aba1,857f4517b5e2aacf6899e489936ec5a8,50.00,Oklahoma,No,Grades 6-8,1113.15,suburban,Oklahoma,8,375.00,5,Math & Science,"Applied Sciences, Health & Life Science",Supplies,"Carolina Biological Supply Company,Carolina Bi..."
1,00070fd37d3e8b5b7c08a4a0ba22aba1,eddfdd15f9c22fe23b306b7f54918c81,50.00,Oklahoma,No,Grades 9-12,388.52,suburban,Oklahoma,6,370.13,2,Music & The Arts,Visual Arts,Supplies,"Amazon Business,Amazon Business"
2,0015dc157335e5ad6f569e5264bbf33e,52f352059701bb7c54990de75f9c108d,50.00,Maryland,Yes,Grades PreK-2,728.87,urban,Maryland,5,718.28,20,"Special Needs, Music & The Arts","Special Needs, Visual Arts",Supplies,"Amazon Business,Amazon Business,Amazon Busines..."
3,0015dc157335e5ad6f569e5264bbf33e,ded87d79ea309cb47686ed54bf4f3f2d,41.00,Maryland,Yes,Grades PreK-2,426.35,urban,Maryland,2,143.16,11,"Applied Learning, Special Needs","Early Development, Special Needs",Books,"AKJ Education,AKJ Education,AKJ Education,AKJ ..."
4,00199e3565635f8a5ebefd3b5985a7f3,3faed6ae4805456447f2b9f22cf0c950,238.65,Massachusetts,No,Grades 3-5,561.53,urban,Massachusetts,1,238.65,3,Health & Sports,"Health & Wellness, Team Sports",Sports & Exercise Equipment,"School Specialty,Staples Advantage,School Spec..."

In [10]:
cosine_df['Amount Needed'] = cosine_df['Project Cost'] - cosine_df['Total Donation Amt Received']
cols_to_drop = ['Donation Amount','Project Cost','Total Donation Amt Received']
cosine_df_final = cosine_df[cosine_df.columns.drop(cols_to_drop)]
cosine_df_final.head()

c:\users\me\desktop\pythonapp\testprojs\venv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Donor ID,Project ID,Donor State,Donor Is Teacher,Project Grade Level Category,School Metro Type,School State,# Donations Received,Teacher Project Posted Sequence,Project Subject Category Tree,Project Subject Subcategory Tree,Project Resource Category,Resource Vendor Name,Amount Needed
0,00070fd37d3e8b5b7c08a4a0ba22aba1,857f4517b5e2aacf6899e489936ec5a8,Oklahoma,No,Grades 6-8,suburban,Oklahoma,8,5,Math & Science,"Applied Sciences, Health & Life Science",Supplies,"Carolina Biological Supply Company,Carolina Bi...",738.15
1,00070fd37d3e8b5b7c08a4a0ba22aba1,eddfdd15f9c22fe23b306b7f54918c81,Oklahoma,No,Grades 9-12,suburban,Oklahoma,6,2,Music & The Arts,Visual Arts,Supplies,"Amazon Business,Amazon Business",18.39
2,0015dc157335e5ad6f569e5264bbf33e,52f352059701bb7c54990de75f9c108d,Maryland,Yes,Grades PreK-2,urban,Maryland,5,20,"Special Needs, Music & The Arts","Special Needs, Visual Arts",Supplies,"Amazon Business,Amazon Business,Amazon Busines...",10.59
3,0015dc157335e5ad6f569e5264bbf33e,ded87d79ea309cb47686ed54bf4f3f2d,Maryland,Yes,Grades PreK-2,urban,Maryland,2,11,"Applied Learning, Special Needs","Early Development, Special Needs",Books,"AKJ Education,AKJ Education,AKJ Education,AKJ ...",283.19
4,00199e3565635f8a5ebefd3b5985a7f3,3faed6ae4805456447f2b9f22cf0c950,Massachusetts,No,Grades 3-5,urban,Massachusetts,1,3,Health & Sports,"Health & Wellness, Team Sports",Sports & Exercise Equipment,"School Specialty,Staples Advantage,School Spec...",322.88

In [11]:
len(cosine_df_final.columns)

14

In [13]:
variables_drop = ['Donor ID','Project ID']
variable_df = cosine_df_final[cosine_df_final.columns.drop(variables_drop)]

import prince
famd = prince.FAMD(n_components=13)#n_components=2,n_iter=3,copy=True,engine='auto',random_state=42)
famdfit = famd.fit(variable_df)
famdfit.transform(variable_df).head() #Each column stands for a principal component whilst each row stands a row in the original dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,394.750877,176.158135,10.639846,245.524732,-347.091433,18.779994,220.419587,-281.210964,-31.183047,-32.645906,40.843195,-239.255935,20.492781
1,383.627239,184.280383,5.518688,234.140010,-348.678031,-7.925007,107.755511,-129.310764,-106.176592,93.265354,1.495419,293.498750,-211.058706
2,498.696589,-214.564322,-229.981057,-277.033778,-112.367340,-59.078436,-34.778345,5.610306,-71.014011,-33.781819,-30.375912,0.124403,-50.254707
3,431.079598,-166.819203,-191.390548,-201.724372,246.339562,-128.852456,-15.612856,29.892942,-60.599190,-105.455070,228.867453,11.650559,-66.960723
4,378.961227,261.538268,262.426111,-119.789145,-4.759076,32.838958,-133.027267,52.998316,-96.426557,-68.333874,43.453226,15.391891,-60.631342

In [14]:
len(variable_df.columns)

12

In [15]:
dir(famdfit)

['U_',
 'V_',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_X_global',
 '_check_and_prepare_input',
 '_get_param_names',
 '_row_coordinates_from_global',
 'all_nums_',
 'cat_one_hots_',
 'column_correlations',
 'copy',
 'eigenvalues_',
 'engine',
 'explained_inertia_',
 'fit',
 'fit_transform',
 'get_params',
 'groups',
 'n_components',
 'n_iter',
 'normalize',
 'partial_factor_analysis_',
 'partial_row_coordinates',
 'plot_partial_row_coordinates',
 'plot_row_coordinates',
 'random_state',
 'rescale_with_mean',
 'rescale_with_std',
 'row_contributions',
 'row_coordinates',
 'row_cosine_similarities',
 'row_standard_coordinates',
 's_',
 'set_params',
 'total_inertia_',
 'transform']

In [23]:
famdfit.groups['Categorical']

['Donor Is Teacher',
 'Project Subject Category Tree',
 'School State',
 'Resource Vendor Name',
 'School Metro Type',
 'Project Grade Level Category',
 'Project Subject Subcategory Tree',
 'Project Resource Category',
 'Donor State']

In [36]:
sorted(famdfit.groups)

['Categorical', 'Numerical']

In [34]:
for name, fa in sorted(famdfit.partial_factor_analysis_.items()):  # doctest: +ELLIPSIS
    print('{} eigenvalues: {}'.format(name, fa.eigenvalues_))
    print(len(fa.eigenvalues_))

Categorical eigenvalues: [0.302179396132305, 0.26353764140456243, 0.2550803719469034, 0.24021551116590045, 0.2378918859858008, 0.23274839591500807, 0.22931164286035424, 0.2277237256867563, 0.22589129941296493, 0.22346228821759642, 0.2188548480909755, 0.21484322814786264, 0.21080974993078008]
13
Numerical eigenvalues: [1.1224184672202904, 1.003677035083628, 0.8739044976960839]
3

# Number of categorical eigenvalues don't match up to number fo categorical items

In [17]:
famdfit.groups['Numerical']

['# Donations Received', 'Teacher Project Posted Sequence', 'Amount Needed']

In [19]:
dir(famdfit.partial_factor_analysis_)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [21]:
dir(famdfit.partial_factor_analysis_.items())

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'isdisjoint']

In [30]:
dir(famdfit.partial_factor_analysis_['Categorical'])

['U_',
 'V_',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_param_names',
 'col_masses_',
 'column_coordinates',
 'copy',
 'eigenvalues_',
 'engine',
 'explained_inertia_',
 'fit',
 'fit_transform',
 'get_params',
 'n_components',
 'n_iter',
 'one_hot_',
 'plot_coordinates',
 'random_state',
 'row_coordinates',
 'row_masses_',
 's_',
 'set_params',
 'total_inertia_',
 'transform']

In [33]:
famdfit.partial_factor_analysis_['Categorical'].total_inertia_

550.0

In [ ]:
variable_contribution = famdfit.explained_inertia_
normed = [i/sum(variable_contribution) for i in variable_contribution]
header_list = list(variable_df.columns.values)
variable_contribution_df = pd.DataFrame([normed]) #,columns=header_list)
variable_contribution_df.head()
#The explained inertia represents the percentage of the inertia each principal component contributes. It sums up to 1 if the n_components property is equal to the number of columns in the original dataset. you The explained inertia is obtained by dividing the eigenvalues obtained with the SVD by the total inertia, both of which are also accessible.
#pca.eigenvalues_
#pca.total_inertia_

In [ ]:
famdfit.partial_row_coordinates(variable_df)

In [ ]:
famdfit.eigenvalues_

In [ ]:
famdfit.total_inertia_

In [ ]:
famdfit.explained_inertia_

In [ ]:
famdfit.eigenvalues_/famdfit.total_inertia_

In [ ]:
plt.plot(np.cumsum(normed))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')